.gitignore
=> fix:gitignore

owl/.env_template, owl/run.py
**Sync with camel usage** [https://github.com/camel-ai/camel/blob/master/camel/types/enums.py](https://github.com/camel-ai/camel/blob/master/camel/types/enums.py)
Configuration updates:
* [`owl/.env_template`](diffhunk://#diff-b9098453c4c8f30c6c42468743b4b2c3857e8340a14085267b3141ef2729b059R1-R4): Added default values for `DEFAULT_MODEL_PLATFORM_TYPE` and `DEFAULT_MODEL_TYPE`, and an empty placeholder for `OPENAI_API_BASE_URL`.
Model creation updates:
* [`owl/run.py`](diffhunk://#diff-b53e9aee7ba850b4cb127e43bc76c1046145af01193cff5fbb6b05cfc1eaccf8L25-R32): Updated the `construct_society` function to use `ModelPlatformType.DEFAULT` and `ModelType.DEFAULT` instead of hardcoding `ModelPlatformType.OPENAI` and `ModelType.GPT_4O`.
=> feat: Temporary support for multiple model access point configurations

.dockerignore, DOCKER_README.md, Dockerfile, build_docker.bat, build_docker.sh, check_docker.bat, check_docker.sh, docker-compose.yml, owl/run_qwq_demo.py, run_in_docker.bat, run_in_docker.sh
still in chinese,English will be done later
=> feat：add docker

.container/Dockerfile, .container/build_docker.bat, .container/build_docker.sh, .container/check_docker.bat, .container/docker-compose.yml, .container/run_in_docker.bat, .container/run_in_docker.sh
findstr "owl.*Up"假设容器名称包含"owl"，如果改变了容器名可能会失效
5秒的固定等待时间可能不够，可以考虑使用循环检查容器是否真正就绪
xvfb-python命令假设容器中有此命令，如果容器配置变更可能需要更新
原来的docker compose 文件没有处理好路径问题, 做了如下修改
```yaml
context: ..
dockerfile: .container/Dockerfile
```
=> optimization bat

.container/build_docker.bat, .container/check_docker.bat, .container/run_in_docker.bat
由于我没有在 windows 上进行测试，导致错误。
window 上的  `|`,   我理解错了。  
```bat
chcp 65001 >nul
```
解决中文乱码的问题。
close #147
=> 修复  | 语法错误，中文乱码

owl/utils/enhanced_role_playing.py
Sometimes, the LLM requests code tests with user input, which is not feasible in an automated environment. This change will disable interactive input for code-related tasks.
=> disable interactive mode for code test and debug

README.md
This PR updates the README.md by adding a high-quality English version of the OWL demo video.
=> docs: update demo video link in README.md

README.md, README_zh.md, owl/.env_template, owl/app.py, owl/run_ollama.py
=> add Ollama API to GUI

owl/app.py
=> enhance_web_env

owl/run_qwen_mini_zh.py, owl/run_qwen_zh.py
The actual test shows that QWEN_VL_MAX rarely uses tools, so QWEN_MAX is preferred in non-multimodal scenarios.
=> Update qwen demo

owl/run_gaia_roleplaying.py, owl/utils/enhanced_role_playing.py
Fix the following errors:
```
- camel.utils.gaia - WARNING - [Errno 2] No such file or directory: 'results/result.json'
```
```
- camel.utils.gaia - ERROR - Error in processing task: 'ChatAgent' object has no attribute 'model_config_dict
```
=> fix gaia bugs

owl/run_gaia_roleplaying.py, owl/utils/gaia.py
Fix the following error:
``` AttributeError: 'Logger' object has no attribute 'success' ```
Current logger in `camel.logger` does not have `'success'`.
=> fix logger bug

owl/utils/document_toolkit.py, owl/utils/gaia.py
- Continue the document process when Chunkr is not valid.
- Add logger info for the numbers of unfinished tasks.
=> fix chunkr use bug

.container/Dockerfile, .container/docker-compose.yml, README.md
Add running with prebuilt docker images.
=> Docs: Add Docker option - running pre-built image.

owl/webapp.py, owl/webapp_zh.py
Improve the log-display box by enabling Markdown rendering and using clear role labels to enhance readability.
=> feat: improve webapp log-display box

examples/run_cli.py
Help owl add cli mode.User can choose the model, platform, language and question in command line.
=> feat: add cli mode

community_usecase/virtual_fitting_room/readme.md, community_usecase/virtual_fitting_room/run_gpt4o.py
This code example can automatically search for suitable trending products from your designated websites (e.g. Uniqlo) and show you realistic try-on effects with different virtual models (you can also use your own photo as the model to get a more intuitive try-on experience). All with one prompt 🪄
=> add community use case: virtual fitting room

.gitignore
Add tmp/ directory to .gitignore
=> chore: ignore temporary runtime files

community_usecase/learning-assistant/README.md, community_usecase/learning-assistant/run_gpt4o.py
This code example searches the internet for relevant learning materials depending on the user's knowledge level and devises a concrete learning roadmap all tailored to the user.
=> Community Usecase - learning assistant

community_usecase/cooking-assistant/README.md, community_usecase/cooking-assistant/run_gpt4o.py
This code example searches for recipes on the internet based on the ingredients you have, refines the content based on a dieterary restriction and generates shopping lists.
=> Community contribution - cooking assistant

community_usecase/virtual_fitting_room/run_gpt4o.py
resub a new PR as requested to avoid conflicts
=> add community usecase: virtual fitting room

.container/Dockerfile
Hi,
When checking the Dockerfile with Hadolint, it complains with msg SC2028 from ShellCheck: "_echo won't expand escape sequences. Consider printf." see https://github.com/koalaman/shellcheck/wiki/SC2028
So replacing echo with printf where requested by Hadolint.
=> dev Dockerfile: removing 2 issues raised by Hadolint

README_ja.md
I created Japanese translated README.
=> docs: add Japanese README

community_usecase/Mcp_use_case/Content_curator.py, community_usecase/Mcp_use_case/Readme.md, community_usecase/Mcp_use_case/mcp_servers_config.json
=> Use Case : Add example in Community Use Cases

examples/run_mistral.py, owl/webapp.py
Hi,
fresh version of https://github.com/camel-ai/owl/pull/433 including changed requested in review of this previous PR
=> run module for Mistral models

README.md, README_zh.md, examples/mcp_sse_config.json, examples/run_mcp_sse.py
This PR supports an example that enables MCP protocol transmission via SSE.
After PR [#1999](https://github.com/camel-ai/camel/pull/1999) is merged, the MCP solution of the Camel-based SSE server will be updated.
=> add mcp_sse example

examples/run_novita_ai.py, owl/.env_template, owl/webapp.py, owl/webapp_zh.py
The related PR: [feat: Add a new llm provider - novita](https://github.com/camel-ai/camel/pull/2284)
=> feat: Add a new llm provider - novita

examples/run_novita_ai.py
Change the default model of novita ai from "NOVITA_LLAMA_4_MAVERICK_17B" to "NOVITA_LLAMA_4_SCOUT_17B"
=> feat: Replace the default model
